### PR TITLE
Create associative entities, configure them with fluentAPI, fix colum…

### LINKED ISSUE #10: Create associative entities, configure them with fluentAPI
Create and configure
- UserRole
- MasterProfile
- MasterCategory

Apply migration

### PR DESCRIPTION
**Pull request by Seztor**
Create associative entities, configure them with fluentAPI, fix column name from camel to snake case

### CODE REVIEW

File: HouseholdServices.Infrastructure/Data/Configurations/MasterProfileConfiguration.cs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+        builder.HasKey(masterProfile => masterProfile.UserId);
+
+        builder.Property(masterProfile => masterProfile.UserId)
+            .HasColumnName("user_id");
+
+        builder.Property(masterProfile => masterProfile.Description)
+            .HasColumnName("description")
+            .IsRequired()
+            .HasMaxLength(2000);
```
Comment (avd1enko) [inline HouseholdServices.Infrastructure/Data/Configurations/MasterProfileConfiguration.cs:21]: не сходится с IDEF1X, там ограничение 500, здесь 2000

**Review by avd1enko — APPROVED** [review]
